### GET Request to retrieve player with id == 1
GET http://localhost:8083/api/players/1
Accept: application/json

### GET ALL PLAYERS
GET http://localhost:8083/api/players/
Accept: application/json

### CREATE A PLAYER

PUT http://localhost:8083/api/players/
Content-Type: application/json

{
  "name": "John Best1",
  "clubId": 3,
  "overall": 80
}

### Update
PATCH http://localhost:8083/api/players/
Content-Type: application/json

{
  "id": 1,
  "name": "best",
  "clubId": 1,
  "overall": 90
}

### delete
DELETE http://localhost:8083/api/players/1
Content-Type: application/json

### get club with id
GET http://localhost:8083/api/clubs/1
Accept: application/json

### get all clubs
GET http://localhost:8083/api/clubs/
Accept: application/json

### create a club
PUT http://localhost:8083/api/clubs/
Content-Type: application/json

{
  "clubName": "new club",
  "stars": 3
}

### update
PATCH http://localhost:8083/api/clubs/
Content-Type: application/json

{
  "id": 1,
  "clubName": "new updated club",
  "stars": 3
}

### delete
DELETE http://localhost:8083/api/clubs/1

###
GET http://localhost:8081/api/players/club/1
Accept: application/json

